services:
  postgres:
    image: postgres:17

    container_name: music-catalog-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: music_catalog
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_user -d music_catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
